### ISSUE TITLE
Aube is not in auryn-0.5

### ISSUE THREAD

**Issue by Haffi112** [fzenke/pub2015orchestrated#1]
Hi,

I was running these simulations with auryn-0.5 and the rf1.pat file was always empty. I then saw that in the bootstrap.sh file that aube is called to create rf1.e.ras from a .bras file. But auryn-0.5 does not generate .bras files so I found it strange that this is referred to in the bootstrap.sh file.

My fix was to replace rf1.e.ras with rf1.0.e.ras and not call aube. I think this is correct but please correct me if I'm wrong.

In any case, I think it would be nice if this issue was fixed.

Thank you in advance! I'm still just starting to grasp things so I don't want to send a pull request just yet.

**Comment by fzenke** [comment]
Hey,

thanks for pointing this out. Yes, there is indeed a problem. Your
workaround is correct if you are not running in parallel, otherwise you
should combine all the spikes from rf1.*.e.ras into rf1.e.ras.

Something like this will do the job
sort -g -m rf1.*.e.ras > rf1.e.ras

Otherwise you are only analyzing spikes from a fraction of the cells in
the population. I will commit an updated version for bootstrap.sh
shortly to fix this.
